name: Publish Docker images to GitHub Container Registry

on:
  push:
    branches:
      - master

jobs:
  publish-docker-images:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Publish Django Docker image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.PUBLISH_DOCKER_IMAGES_PAT }}
        containerRegistry: true
        context: django/
        imageName: django
        tag: '2.2.18'

    - name: Publish Django with WeasyPrint Docker image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.PUBLISH_DOCKER_IMAGES_PAT }}
        containerRegistry: true
        context: django-with-weasyprint/
        imageName: django
        tag: '2.2.18-with-weasyprint'
